apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rng-hpa # optional: rng, hasher
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rng # optional: rng, hasher
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 10
      policies:
      - type: Percent
        value: 20  # max up 20%
        periodSeconds: 60  # per 60s
      - type: Pods
        value: 2  # max 2 pod
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 30
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5
